version: '2'

services:
    zookeeper:
        image: wurstmeister/zookeeper
        ports:
            - "2181:2181"
        networks:
            - comp_default

    kafka:
        image: cuongtransc/kafka:2.0.0
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        networks:
            - comp_default
        environment:
            # KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
            KAFKA_ADVERTISED_HOST_NAME: 172.17.0.1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        # volumes:
        #   - /var/run/docker.sock:/var/run/docker.sock

networks:
    comp_default:
        external: true
